Repository boostcampwm-2024/refactor-web42-stop-troublepainter, pull requests merged in 2025-02, with the labels that each got.

#43 🐛fix(server/main.ts): connectToRedis가 빠진 것을 추가
  server/src/main.ts
Labels: 🐛 bug

#52 Feature/#48 서버에서 가상 캔버스에 그림 그리기
  pnpm-lock.yaml
  server/package.json
  server/src/common/services/canvas.service.spec.ts
  server/src/common/services/canvas.service.ts
Labels: :white_check_mark: test

#58 Feature/#57 OCR로 인식된 텍스트의 바운더리로 스트로크를 제거하는 CRDT 메시지 생성
  server/src/common/services/canvas.service.spec.ts
  server/src/common/services/canvas.service.ts
Labels: ✨feature

#61 fix: 다른 사람의 그림이 안보이는 오류 해결
  client/src/hooks/socket/useDrawingSocket.ts
Labels: 🐛 bug

#62 Feature/#54
  client/src/hooks/socket/useDrawingSocket.ts
  core/crdt/LWWMap.ts
  server/src/common/clova-ocr.ts
  server/src/common/clova-studio.ts
  server/src/drawing/drawing.gateway.ts
  server/src/game/game.gateway.ts
  server/src/game/game.module.ts
  server/src/redis/redis.service.ts
Labels: ✨feature

#65 Refactor/#63 캔버스 내 글자 지우는 부분을 비동기로 변경
  server/src/drawing/drawing.gateway.ts
  server/src/game/game.gateway.ts
Labels: 🔨 refactor

#70 Feature/#69 배경음 및 효과음 기본 끄기로 설정
  client/src/hooks/useBackgroundMusic.ts
  client/src/utils/soundManager.ts
Labels: ✨feature

#73 bug/#72 OCR 동작 시간 동안 채팅이 전송되는 오류 수정
  client/src/components/chat/ChatInput.tsx
Labels: 🐛 bug

#76 Refactor/#75 pureimage에서 node-canvas로 변경
  pnpm-lock.yaml
  server/package.json
  server/src/common/services/canvas.service.ts
Labels: 🔨 refactor

#77 Feature/#71 Clova Studio를 적용하여 제시어와 연관된 단어 발견 시 패널티 적용
  server/src/common/clova-studio.ts
  server/src/game/game.gateway.ts
  server/src/game/game.module.ts
  server/src/game/game.service.ts
Labels: ✨feature

#80 🏗️build(docker-build/prod/nginx.conf): http 2, 3 버전 활성화
  docker-build/prod/nginx.conf
Labels: :earth_asia: deploy

#83 Refactor/#82 그림을 분석하는 시간을 10초로 줄이기
  client/pnpm-lock.yaml
  client/postcss.config.js
  client/public/site.webmanifest
  client/src/assets/lottie/help/fifth.json
  client/src/assets/lottie/help/first.json
  client/src/assets/lottie/help/fourth.json
  client/src/assets/lottie/help/second.json
  client/src/assets/lottie/help/third.json
  client/src/components/quiz/QuizStage.tsx
  client/src/hooks/socket/useDrawingSocket.ts
  client/src/hooks/socket/useGameSocket.ts
  core/.prettierrc
  server/src/game/game.gateway.ts
Labels: 🔨 refactor

#87 Feature/#86 패널티 받으면 토스트 메시지 띄우기
  client/src/hooks/socket/useGameSocket.ts
  core/crdt/test/drawing-text.spec.ts
  server/src/game/game.gateway.ts
Labels: ✨feature

#95 refactor/#89 Clova Studio로 부정확한 OCR 성능 개선하기
  server/src/common/clova-studio.ts
Labels: 🔨 refactor

#101 Refactor/#97 server 에러 수정, nginx 설정 분리
  .gitignore
  docker-build/dev/Dockerfile.server
  docker-build/dev/nginx.conf
  docker-build/prod/Dockerfile.nginx
  docker-build/prod/Dockerfile.server
  docker-build/prod/docker-compose.yml
  docker-build/prod/nginx.http.conf
  docker-build/prod/nginx.main.conf
  server/src/artillery/README.md
  server/src/artillery/local/functions.js
  server/src/artillery/local/game-test.yml
  server/src/artillery/server/functions.js
  server/src/artillery/server/game-test.yml
Labels: 🔨 refactor

#104 Refactor/#102#103 클로버 스튜디오 단어 인식률 NaN 문제 및 캔버스 여백 추가
  server/src/common/clova-studio.ts
  server/src/common/services/canvas.worker.ts
Labels: 🔨 refactor, 🐛 bug

#107 fix: 캔버스 여백 좌표 계산 수정
  server/src/common/services/canvas.worker.ts
Labels: 🐛 bug

#111 chore/#110 불필요한 console.log 제거
  client/src/hooks/socket/useGameSocket.ts
  client/src/stores/socket/chatWorker.ts
  client/src/stores/socket/gameWorker.ts
  client/src/stores/socket/socketWorker.ts
  core/crdt/test/drawing-utils.ts
Labels: 🔨 refactor

#113 fix: panelty에서 penalty로 수정
  client/src/hooks/socket/useGameSocket.ts
Labels: 🐛 bug
