Repository boostcampwm-2024/refactor-web42-stop-troublepainter, pull requests merged in 2025-01, with the labels that each got.

#3 #1 drawing 모듈 테스트 코드 추가
  server/src/drawing/drawing.gateway.spec.ts
  server/src/drawing/drawing.gateway.ts
  server/src/drawing/drawing.repository.spec.ts
  server/src/drawing/drawing.repository.ts
  server/src/drawing/drawing.service.spec.ts
Labels: :white_check_mark: test

#5 Test/#2 server chat module 테스트 코드 추가
  pnpm-lock.yaml
  server/package.json
  server/src/chat/chat.gateway.spec.ts
  server/src/chat/chat.module.spec.ts
  server/src/chat/chat.repository.spec.ts
  server/src/chat/chat.service.spec.ts
  server/tsconfig.json
Labels: :white_check_mark: test

#7 Deploy#6 배포 관련 스크립트 변경
  .github/workflows/client-ci-cd.yml
  .github/workflows/server-ci-cd.yml
  Dockerfile.nginx
  Dockerfile.server
  nginx.conf
Labels: :earth_asia: deploy

#8 Dev be to develop
  .github/workflows/client-ci-cd.yml
  .github/workflows/server-ci-cd.yml
  Dockerfile.nginx
  Dockerfile.server
  nginx.conf
  pnpm-lock.yaml
  server/package.json
  server/src/chat/chat.gateway.spec.ts
  server/src/chat/chat.module.spec.ts
  server/src/chat/chat.repository.spec.ts
  server/src/chat/chat.service.spec.ts
  server/src/drawing/drawing.gateway.spec.ts
  server/src/drawing/drawing.gateway.ts
  server/src/drawing/drawing.repository.spec.ts
  server/src/drawing/drawing.repository.ts
  server/src/drawing/drawing.service.spec.ts
  server/tsconfig.json
Labels: :earth_asia: deploy

#9 Test/#4 drawing 모듈 e2e 테스트
  pnpm-lock.yaml
  server/docker-compose.yml
  server/package.json
  server/src/drawing/drawing.gateway.e2e.spec.ts
  server/src/drawing/drawing.gateway.integration.spec.ts
  server/src/drawing/drawing.gateway.ts
  server/src/redis/redis.service.ts
  server/src/test-docker.sh
Labels: :white_check_mark: test

#11 🐛fix(client/api.config.ts): troublepainter site로 하드코딩된 부분을 우리 사이트 주소로 변경
  client/src/utils/checkProduction.ts
Labels: 🐛 bug

#17 Bug/#15 handleConnection 코드 문제 해결
  .github/workflows/apply-issue-template.yml
  client/src/utils/checkProduction.ts
  server/src/chat/chat.gateway.ts
Labels: 🐛 bug

#21 Test/#20 플레이 라이트 성능 테스트 자동화
  .gitignore
  core/crdt/test/drawing-utils.ts
  core/crdt/test/random-drawing-performance.spec.ts
  core/crdt/test/random-drawing.spec.ts
  core/crdt/test/test-utils.ts
  core/playwright.config.ts
Labels: :white_check_mark: test

#27 Refactor/#22
  pnpm-lock.yaml
  server/package.json
  server/src/game/game.gateway.ts
  server/src/game/game.repository.ts
  server/src/game/game.service.ts
Labels: 🔨 refactor

#30 Refactor/#29 프론트엔드 최적화
  client/package.json
  client/src/components/canvas/GameCanvas.tsx
  client/src/handlers/socket/drawingSocket.handler.ts
  client/src/hooks/canvas/useDrawing.ts
  client/src/hooks/canvas/useDrawingOperation.ts
  client/src/hooks/canvas/useDrawingState.ts
  client/src/hooks/useCoordinateScale.ts
  core/crdt/test/drawing-performance.spec.ts
  core/crdt/test/drawing-utils.ts
  core/crdt/test/event-data-1.json
  core/crdt/test/event-data-2.json
  core/crdt/test/event-data-3.json
  core/tsconfig.json
  pnpm-lock.yaml
Labels: 🔨 refactor, :white_check_mark: test

#32 Refactor/#15 redis adaptor socket io에 적용하기
  package.json
  pnpm-lock.yaml
  server/package.json
  server/src/game/game.gateway.ts
  server/src/main.ts
  server/src/redis/redis.adaptor.ts
Labels: 🔨 refactor

#35 Refactor/shared worker/#14
  client/src/components/chat/ChatInput.tsx
  client/src/handlers/socket/chatSocket.handler.ts
  client/src/handlers/socket/gameSocket.handler.ts
  client/src/hooks/socket/useChatSocket.ts
  client/src/hooks/socket/useGameSocket.ts
  client/src/hooks/useStartButton.tsx
  client/src/layouts/GameLayout.tsx
  client/src/stores/socket/chatWorker.ts
  client/src/stores/socket/gameWorker.ts
  client/src/stores/socket/socket.config.ts
  client/src/stores/socket/socketWorker.ts
  client/src/types/worker.d.ts
  client/tsconfig.app.json
Labels: 🔨 refactor

#40 ♻️refactor(socket.config.ts): 클라이언트의 socket.io 설정을 websocket만 사용하게 변경
  client/src/stores/socket/socket.config.ts
Labels: 🔨 refactor
